### PR TITLE
molecule test ``openshift_auth`` - host resolution

### LINKED ISSUE #35: `openshift_auth` molecule tests only work when run from a pod in the cluster
##### SUMMARY

The molecule tests for `openshift_auth` have the host hardcoded to `https://kubernetes.default.svc`, which is the fqdn for the API server when running as a pod in the cluster. We should make the task able to determine whether it's running incluster or not, and have it determine the proper host. Ideally, this can be done via the planned `community.kubernetes.k8s_cluster_info` module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

tests
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

### PR DESCRIPTION
**Pull request by abikouo**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/943

##### SUMMARY

close #35

##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

molecule test scenario ``openshift_auth``

### CODE REVIEW

**Review by fabianvf — APPROVED** [review]
/lgtm

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Pull request merged**
