### PR TITLE
Update README, CONTRIBUTING.md: freenode -> libera.chat

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-community/community-topics/issues/19

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
CONTRIBUTING.md, README.md

### CODE REVIEW

**Review by abikouo — APPROVED** [review]

**Comment by Andersson007** [comment]
hi, `Pending — Not mergeable. Needs bugzilla/valid-bug label.` How we can get it?

**Comment by abikouo** [comment]
> hi, `Pending — Not mergeable. Needs bugzilla/valid-bug label.` How we can get it?

going to be disabled on this https://github.com/openshift/release/pull/18825
now we are just skipping this.
@Akasurde could you please merge this one ?

**Comment by Andersson007** [comment]
@abikouo I can, no problem. Wanted to be sure that everything is under control. Thank you all folks!

**Pull request merged**
