### PR TITLE
Restrict kubernetes.core dependency version

### PR DESCRIPTION
**Pull request by gravesm**
##### SUMMARY

In order to better coordinate releases between this collection and the
kubernetes.core collection we need to use a more restrictive dependency
version range.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

collection

##### ADDITIONAL INFORMATION

N/A

### CODE REVIEW

**Review by fabianvf — APPROVED** [review]

**Comment by gravesm** [comment]
Rebased on #67 so everything *should* pass except downstream sanity.

**Comment by gravesm** [comment]
@fabianvf I added a missing changelog fragment and rebased again to pick up the changes from #68. With the release of ansible 2.9.18 last night, the full ci suite should hopefully pass, now.

**Pull request merged**
