### PR TITLE
Issue #60: Release version 1.0.1.

### PR DESCRIPTION
**Pull request by geerlingguy**
Issue #60.﻿

### CODE REVIEW

**Comment by geerlingguy** [comment]
I'm getting:

```
ERROR: Found 1 rstcheck issue(s) which need to be resolved:
ERROR: CHANGELOG.rst:1:0: Title overline too short.
```

The line in question:

```
============================
 OKD Collection Release Notes
============================
```

**Comment by geerlingguy** [comment]
Er... after downstream build runs, it _is_ wrong:

```
============================
OpenShift Collection Release Notes
============================
```

**Comment by jillr** [comment]
artifact builds when testing this locally on linux, lgtm

**Comment by felixfontein** [comment]
If you do a search-and-replace, yes, you need to adjust the number of `=`s :) What you could also do is change the collection's name in `changelogs/config.yaml` and run `antsibull-changelog generate`. That will re-generate the .rst file from the config and `changelogs/changelog.yaml`.

**Comment by geerlingguy** [comment]
@felixfontein - Our downstream build process is already a big ball of wax, what's one more step? :D

**Pull request merged**
